#!/usr/bin/env bats
# covers: scripts/install-hooks.sh
#
# Tests for v0.27.0 #173 Layer 5: chmod +x self-heal across both
# hooks/*.sh and .claude/hooks/*.sh.

setup() {
	SCRIPT="${BATS_TEST_DIRNAME}/../../../scripts/install-hooks.sh"
	TEST_TMP=$(mktemp -d -t install-hooks-chmod.XXXXXX) || {
		echo "FATAL: mktemp failed" >&2
		return 1
	}
	mkdir -p "$TEST_TMP/scripts" "$TEST_TMP/hooks" "$TEST_TMP/.claude/hooks"
	# Initialize a git repo so REPO_ROOT inference works.
	(cd "$TEST_TMP" && git init -q && git config user.email test@x && git config user.name test)
	# Symlink the script under test into the test repo.
	ln -s "$SCRIPT" "$TEST_TMP/scripts/install-hooks.sh"
}

teardown() {
	# shellcheck disable=SC2164
	cd /tmp
	if [ -n "${TEST_TMP:-}" ] && [ -d "$TEST_TMP" ] && [[ $TEST_TMP == */install-hooks-chmod.* ]]; then
		rm -rf "$TEST_TMP"
	fi
}

@test "--check flags non-executable hook as drift" {
	# Stage non-executable hook
	echo '#!/bin/bash' >"$TEST_TMP/hooks/test-hook.sh"
	chmod 644 "$TEST_TMP/hooks/test-hook.sh"
	# Stub pre-commit + git wrapper bits the script needs
	cat >"$TEST_TMP/.git/hooks/pre-commit" <<'EOF'
#!/bin/sh
echo "# pre-commit"
EOF
	chmod +x "$TEST_TMP/.git/hooks/pre-commit"
	# Stub gate src
	echo '#!/bin/sh' >"$TEST_TMP/hooks/pre-push-pipeline-gate.sh"
	chmod +x "$TEST_TMP/hooks/pre-push-pipeline-gate.sh"
	# Write a wrapper at .git/hooks/pre-push matching template
	cat >"$TEST_TMP/.git/hooks/pre-push" <<'EOF'
#!/bin/sh
# Auto-generated by scripts/install-hooks.sh — DO NOT EDIT.
# Re-run scripts/install-hooks.sh to regenerate after plugin updates.
# REPO_ROOT resolved at runtime so the wrapper survives `mv repo` and
# works in git worktrees. Git invokes pre-push hooks with cwd = repo
# worktree root, so bare `git rev-parse --show-toplevel` works.
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || {
	echo "pre-push wrapper: cannot resolve REPO_ROOT (not in a git working tree?) — re-run scripts/install-hooks.sh" >&2
	exit 2
}
exec "$REPO_ROOT/hooks/pre-push-pipeline-gate.sh" "$@"
EOF
	chmod +x "$TEST_TMP/.git/hooks/pre-push"
	(
		cd "$TEST_TMP" || exit 1
		run "$TEST_TMP/scripts/install-hooks.sh" --check
		[ "$status" -eq 1 ]
		[[ $output == *"DRIFT"* ]]
		[[ $output == *"missing +x bit"* ]]
	)
}

@test "install mode restores +x on non-executable hook" {
	echo '#!/bin/bash' >"$TEST_TMP/hooks/test-hook.sh"
	chmod 644 "$TEST_TMP/hooks/test-hook.sh"
	# Stub pre-push gate src
	echo '#!/bin/sh' >"$TEST_TMP/hooks/pre-push-pipeline-gate.sh"
	chmod +x "$TEST_TMP/hooks/pre-push-pipeline-gate.sh"
	# Stub pre-commit on PATH
	mkdir -p "$TEST_TMP/bin"
	cat >"$TEST_TMP/bin/pre-commit" <<'EOF'
#!/bin/bash
exit 0
EOF
	chmod +x "$TEST_TMP/bin/pre-commit"
	(
		# shellcheck disable=SC2030
		export PATH="$TEST_TMP/bin:$PATH"
		cd "$TEST_TMP" || exit 1
		run "$TEST_TMP/scripts/install-hooks.sh"
		[ "$status" -eq 0 ]
		[[ $output == *"+x restored on"* ]] || [[ $output == *"scanned"* ]]
		mode=$(stat -f '%Mp%Lp' "$TEST_TMP/hooks/test-hook.sh" 2>/dev/null || stat -c '%a' "$TEST_TMP/hooks/test-hook.sh")
		[ "$mode" = "755" ] || [ "$mode" = "0755" ]
	)
}

@test "install mode also scans .claude/hooks/" {
	# v0.27.1 #173 Phase 1 r1 fix: chmod loop extended to .claude/hooks/
	echo '#!/bin/bash' >"$TEST_TMP/.claude/hooks/claude-hook.sh"
	chmod 644 "$TEST_TMP/.claude/hooks/claude-hook.sh"
	echo '#!/bin/sh' >"$TEST_TMP/hooks/pre-push-pipeline-gate.sh"
	chmod +x "$TEST_TMP/hooks/pre-push-pipeline-gate.sh"
	mkdir -p "$TEST_TMP/bin"
	cat >"$TEST_TMP/bin/pre-commit" <<'EOF'
#!/bin/bash
exit 0
EOF
	chmod +x "$TEST_TMP/bin/pre-commit"
	(
		# shellcheck disable=SC2030,SC2031
		export PATH="$TEST_TMP/bin:$PATH"
		cd "$TEST_TMP" || exit 1
		run "$TEST_TMP/scripts/install-hooks.sh"
		[ "$status" -eq 0 ]
		mode=$(stat -f '%Mp%Lp' "$TEST_TMP/.claude/hooks/claude-hook.sh" 2>/dev/null || stat -c '%a' "$TEST_TMP/.claude/hooks/claude-hook.sh")
		[ "$mode" = "755" ] || [ "$mode" = "0755" ]
	)
}
