#!/bin/bash
# v4.21 (#520): shared lib for `.claude/scripts/**/*.sh` operational helpers.
#
# WHY this exists: the board/labels/cr scripts all need the same 4-5
# primitives (read ACTIONS_MODE, parse --dry-run, log to .claude/logs/,
# record .last-run timestamps, emit structured warnings). Extracting
# them here keeps each script tight and prevents drift (one script's
# dry-run handling diverging from another's).
#
# Usage: source "$(dirname "$0")/../_common.sh" (adjust depth per caller)
#
# CONTRACT: callers should `set -euo pipefail` before sourcing; helpers
# propagate errors via exit codes, not silent fallbacks.

# Guard against double-source (common when scripts chain-invoke each other).
if [ -n "${SCRIPTS_COMMON_LOADED:-}" ]; then
	return 0 2>/dev/null || true
fi
SCRIPTS_COMMON_LOADED=1

# Resolve REPO_ROOT from any caller depth. Callers ideally set this
# themselves; we fall back to `git rev-parse` only if unset.
: "${REPO_ROOT:=$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
export REPO_ROOT

SCRIPTS_LOG_DIR="$REPO_ROOT/.claude/logs"
SCRIPTS_LAST_RUN_DIR="$REPO_ROOT/.claude/logs/last-run"

# Read ACTIONS_MODE from mode.conf. Returns "local" or "remote"; errors to
# stderr + returns 2 if mode.conf is missing or malformed (loud-fail per
# the feedback_silent_failure memory — never assume local or remote).
scm_actions_mode() {
	local mode_file="$REPO_ROOT/.claude/mode.conf"
	if [ ! -f "$mode_file" ]; then
		echo "scm: .claude/mode.conf not found — cannot determine ACTIONS_MODE" >&2
		return 2
	fi
	local mode
	# `|| true` on the pipeline: under `set -eo pipefail` (which many
	# callers enable before sourcing), `grep` exiting 1 on no-match would
	# propagate through the command substitution and exit the caller
	# silently — bypassing the "ACTIONS_MODE missing" loud-fail below.
	# Strip inline `# ...` comments + surrounding whitespace so
	# `ACTIONS_MODE=local # generated by ...` parses as "local".
	mode=$(grep '^ACTIONS_MODE=' "$mode_file" | head -1 | cut -d= -f2- | cut -d'#' -f1 | tr -d ' ' || true)
	if [ -z "$mode" ]; then
		echo "scm: ACTIONS_MODE missing from $mode_file" >&2
		return 2
	fi
	if [ "$mode" != "local" ] && [ "$mode" != "remote" ]; then
		echo "scm: invalid ACTIONS_MODE='$mode' (expected 'local' or 'remote')" >&2
		return 2
	fi
	printf '%s' "$mode"
}

# Skip the script body unless mode matches. Used by local-backup replicas
# to no-op when ACTIONS_MODE=remote (GitHub Actions is handling it) and
# by pure-local scripts to declare "I only run under local mode".
#
# Usage: scm_require_mode local   # exits 0 with a brief message if mismatched
scm_require_mode() {
	local want="${1:?mode arg required (local|remote)}"
	local have
	if ! have=$(scm_actions_mode); then
		return 2
	fi
	if [ "$have" != "$want" ]; then
		echo "scm: skipping — ACTIONS_MODE=$have, script requires $want" >&2
		exit 0
	fi
}

# Wrap a mutating command with dry-run support. Prints the command that
# would run if SCM_DRY_RUN=1, executes otherwise. Returns the command's
# exit code (or 0 in dry-run).
#
# Usage: scm_run gh issue edit "$N" --add-label "bug"
scm_run() {
	if [ "${SCM_DRY_RUN:-0}" = "1" ]; then
		printf '[dry-run] '
		printf '%q ' "$@"
		printf '\n'
		return 0
	fi
	"$@"
}

# Append a single JSONL line to the script's log file under .claude/logs/.
# Caller passes a script name + JSON fields. The helper adds `ts` + `sha`
# so log lines are self-describing.
#
# Usage: scm_log "board-move-item" '{"issue":123,"column":"In Progress"}'
scm_log() {
	local script="${1:?script name required}"
	# `${2:-{}}` trips bash's brace-expansion parser on the literal `{}`;
	# use an explicit if to fall back to an empty JSON object.
	local fields
	if [ -z "${2:-}" ]; then
		fields='{}'
	else
		fields="$2"
	fi
	mkdir -p "$SCRIPTS_LOG_DIR"
	local sha
	sha=$(git rev-parse --short HEAD 2>/dev/null || echo "no-git")
	local ts
	ts=$(date -u +%Y-%m-%dT%H:%M:%SZ)
	local line
	line=$(jq -cn --arg ts "$ts" --arg sha "$sha" --arg script "$script" --argjson fields "$fields" \
		'{ts: $ts, sha: $sha, script: $script} + $fields' 2>/dev/null) || {
		# If jq fails (malformed $fields), write a diagnostic line rather
		# than silently dropping the log entry — loud-fail per v4.20 pattern.
		# Build the fallback via jq too so ts/sha/script get proper JSON
		# escaping (they're controlled values today but the pattern is
		# robust against future callers passing quotes/backslashes).
		jq -nc --arg ts "$ts" --arg sha "$sha" --arg script "$script" --arg raw "$fields" \
			'{ts: $ts, sha: $sha, script: $script, _error: "jq_failed", raw: $raw}' \
			>>"$SCRIPTS_LOG_DIR/${script}.jsonl"
		return 0
	}
	printf '%s\n' "$line" >>"$SCRIPTS_LOG_DIR/${script}.jsonl"
}

# Record/read a .last-run timestamp (epoch seconds) for a named operation.
# Useful for periodic scripts that want to self-throttle or skip-if-recent.
scm_last_run_set() {
	local name="${1:?name required}"
	mkdir -p "$SCRIPTS_LAST_RUN_DIR"
	date +%s >"$SCRIPTS_LAST_RUN_DIR/$name"
}
scm_last_run_get() {
	local name="${1:?name required}"
	local file="$SCRIPTS_LAST_RUN_DIR/$name"
	[ -f "$file" ] || {
		echo 0
		return 0
	}
	# Validate numeric: a corrupt/partial file would otherwise crash
	# callers doing arithmetic (`$(( $(scm_last_run_get x) + 60 ))`)
	# under set -e. Defaulting to 0 matches the no-file path.
	local val
	val=$(cat "$file")
	if [[ "$val" =~ ^[0-9]+$ ]]; then
		echo "$val"
	else
		echo 0
	fi
}

# Emit a structured warning to stderr in the style the rest of the v4.21
# wrappers use (⚠ prefix + remediation hint). Keeps warnings visually
# consistent across scripts.
scm_warn() {
	echo "⚠ $*" >&2
}

# Loud-fail + exit 2 with a consistent prefix. Use when a pre-condition
# fails (missing flag, malformed arg, missing dependency).
scm_fail() {
	echo "✗ $*" >&2
	exit 2
}
