#!/bin/bash
set -euo pipefail
# v0.9.1 (#47): install-hooks — wire pre-commit + git pre-push gates for
# the plugin repo itself so plugin's own pushes go through the same gates
# consumer repos do.
#
# Idempotent. Safe to re-run.
#
# Usage:
#   scripts/install-hooks.sh           # install everything
#   scripts/install-hooks.sh --check   # verify install (rc=0 clean,
#                                      # rc=1 drift, rc=4 absent)
#   scripts/install-hooks.sh --help

usage() {
	cat <<'EOF'
Usage: scripts/install-hooks.sh [--check] [--help]

Installs pre-commit framework hooks AND the git pre-push gate for the
plugin repo. Idempotent — safe to re-run.

Options:
  --check    Verify install without modifying anything.
  --help     Show this help.

Exit codes:
  0  Install/check succeeded (or --check found clean install).
  1  --check detected DRIFT (installed but misconfigured).
  2  Usage error or repo precondition failed.
  3  Required dependency missing (e.g. pre-commit not in PATH).
  4  --check detected ABSENT install (operator needs to run install).
EOF
}

CHECK_ONLY=0

while [ $# -gt 0 ]; do
	case "$1" in
	--check)
		CHECK_ONLY=1
		shift
		;;
	-h | --help)
		usage
		exit 0
		;;
	*)
		echo "unknown arg: $1" >&2
		usage
		exit 2
		;;
	esac
done

# Derive REPO_ROOT from the script's own location, NOT git rev-parse.
# Reason: a user running this script from inside ANOTHER git repo (via
# absolute path) would otherwise install hooks for the wrong repo.
# CR-CLI Phase 2 caught this. The script lives at <repo>/scripts/
# install-hooks.sh so dirname(BASH_SOURCE)/.. is the repo root.
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)

# Still verify the inferred root IS a git repo — otherwise the hooks
# we're about to install have nowhere to live.
if ! (cd "$REPO_ROOT" && git rev-parse --git-dir >/dev/null 2>&1); then
	echo "install-hooks: $REPO_ROOT is not a git repo (script must live in <repo>/scripts/)" >&2
	exit 2
fi
cd "$REPO_ROOT"

_log() { echo "[install-hooks] $*" >&2; }

# Worktree-safe hook dir: git rev-parse --git-path resolves the per-
# worktree hooks dir (.git/hooks for plain clones, .git/worktrees/<name>/
# hooks for `git worktree add` checkouts, .git/modules/<name>/hooks for
# submodules). Avoid the ../../ hardcode that Phase 1 code-reviewer
# flagged (#47 sub-issue 1 r1).
HOOKS_DIR=$(git rev-parse --git-path hooks)

# --- 1. pre-commit framework hooks --------------------------------------
PRECOMMIT_HOOK="$HOOKS_DIR/pre-commit"

if [ "$CHECK_ONLY" = "1" ]; then
	if [ ! -x "$PRECOMMIT_HOOK" ]; then
		_log "ABSENT: $PRECOMMIT_HOOK not installed — run 'scripts/install-hooks.sh' first"
		exit 4
	fi
	if ! grep -q "pre-commit" "$PRECOMMIT_HOOK" 2>/dev/null; then
		_log "DRIFT: $PRECOMMIT_HOOK not managed by pre-commit framework"
		exit 1
	fi
else
	if ! command -v pre-commit >/dev/null 2>&1; then
		_log "error: pre-commit not in PATH — install with: brew install pre-commit"
		exit 3
	fi
	_log "installing pre-commit hooks..."
	pre-commit install --install-hooks
fi

# --- 2. git pre-push gate (pipeline gate) -------------------------------
# Symlink hooks/pre-push-pipeline-gate.sh → $HOOKS_DIR/pre-push so the
# in-tree script is the source of truth (in-place edits to the target
# script take effect immediately without re-running install).
GATE_SRC="hooks/pre-push-pipeline-gate.sh"
GATE_DST="$HOOKS_DIR/pre-push"

if [ ! -x "$GATE_SRC" ]; then
	_log "error: gate script missing at $GATE_SRC"
	exit 2
fi

if [ "$CHECK_ONLY" = "1" ]; then
	if [ ! -x "$GATE_DST" ]; then
		_log "ABSENT: $GATE_DST not installed — run 'scripts/install-hooks.sh' first"
		exit 4
	fi
	# Wrapper script signature: must `exec` the real gate at the
	# REPO_ROOT-relative path. Drift = wrong target or hand-edited file.
	expected_exec_line="exec \"$REPO_ROOT/$GATE_SRC\" \"\$@\""
	if ! grep -qF "$expected_exec_line" "$GATE_DST"; then
		_log "DRIFT: $GATE_DST does not exec '$REPO_ROOT/$GATE_SRC'"
		_log "  Re-run 'scripts/install-hooks.sh' to regenerate."
		exit 1
	fi
else
	_log "installing pre-push gate at $GATE_DST..."
	# Write a wrapper script in $HOOKS_DIR that exec's the real gate
	# with an absolute path. This is intentionally NOT a symlink:
	# the gate + its helper (list-phase1-agents.sh) use ${BASH_SOURCE[0]}
	# to locate _lib via `dirname/.. /_lib`. Bash's BASH_SOURCE points at
	# the path the script was invoked with — so under a symlink, it
	# resolves to .git/hooks/ → /.git/_lib (which doesn't exist), not
	# the real plugin's hooks/../_lib. macOS readlink lacks -f, so we
	# can't portably canonicalize inside the gate. The wrapper sidesteps
	# this by invoking the real absolute path directly.
	GATE_ABS="$REPO_ROOT/$GATE_SRC"
	if [ ! -x "$GATE_ABS" ]; then
		_log "error: gate script $GATE_ABS missing or not executable"
		exit 2
	fi
	rm -f "$GATE_DST"
	cat >"$GATE_DST" <<EOF
#!/bin/sh
# Auto-generated by scripts/install-hooks.sh — DO NOT EDIT.
# Re-run scripts/install-hooks.sh to regenerate after plugin updates.
exec "$GATE_ABS" "\$@"
EOF
	chmod +x "$GATE_DST"
fi

# --- 3. Summary ----------------------------------------------------------
if [ "$CHECK_ONLY" = "1" ]; then
	_log "✓ all hooks installed + match expected layout"
else
	_log "✓ install complete:"
	_log "    $PRECOMMIT_HOOK → managed by pre-commit framework"
	_log "    $GATE_DST → wrapper script exec-ing $GATE_SRC"
	_log ""
	_log "Verify with: scripts/install-hooks.sh --check"
fi
