#!/bin/bash
set -euo pipefail
# v0.9.1 (#47): install-hooks — wire pre-commit + git pre-push gates for
# the plugin repo itself so plugin's own pushes go through the same gates
# consumer repos do.
#
# Idempotent. Safe to re-run.
#
# Usage:
#   scripts/install-hooks.sh           # install everything
#   scripts/install-hooks.sh --check   # verify install (rc=0 clean,
#                                      # rc=1 drift, rc=4 absent)
#   scripts/install-hooks.sh --help

usage() {
	cat <<'EOF'
Usage: scripts/install-hooks.sh [--check] [--help]

Installs pre-commit framework hooks AND the git pre-push gate for the
plugin repo. Idempotent — safe to re-run.

Options:
  --check    Verify install without modifying anything.
  --help     Show this help.

Exit codes:
  0  Install/check succeeded (or --check found clean install).
  1  --check detected DRIFT (installed but misconfigured).
  2  Usage error or repo precondition failed.
  3  Required dependency missing (e.g. pre-commit not in PATH).
  4  --check detected ABSENT install (operator needs to run install).
EOF
}

CHECK_ONLY=0

while [ $# -gt 0 ]; do
	case "$1" in
	--check)
		CHECK_ONLY=1
		shift
		;;
	-h | --help)
		usage
		exit 0
		;;
	*)
		echo "unknown arg: $1" >&2
		usage
		exit 2
		;;
	esac
done

# Derive REPO_ROOT from the script's own location, NOT git rev-parse.
# Reason: a user running this script from inside ANOTHER git repo (via
# absolute path) would otherwise install hooks for the wrong repo.
# CR-CLI Phase 2 caught this. The script lives at <repo>/scripts/
# install-hooks.sh so dirname(BASH_SOURCE)/.. is the repo root.
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)

# Still verify the inferred root IS a git repo — otherwise the hooks
# we're about to install have nowhere to live.
if ! (cd "$REPO_ROOT" && git rev-parse --git-dir >/dev/null 2>&1); then
	echo "install-hooks: $REPO_ROOT is not a git repo (script must live in <repo>/scripts/)" >&2
	exit 2
fi
cd "$REPO_ROOT"

_log() { echo "[install-hooks] $*" >&2; }

# Worktree-safe hook dir: git rev-parse --git-path resolves the per-
# worktree hooks dir (.git/hooks for plain clones, .git/worktrees/<name>/
# hooks for `git worktree add` checkouts, .git/modules/<name>/hooks for
# submodules). Avoid the ../../ hardcode that Phase 1 code-reviewer
# flagged (#47 sub-issue 1 r1).
HOOKS_DIR=$(git rev-parse --git-path hooks)

# --- 1. pre-commit framework hooks --------------------------------------
PRECOMMIT_HOOK="$HOOKS_DIR/pre-commit"

if [ "$CHECK_ONLY" = "1" ]; then
	if [ ! -x "$PRECOMMIT_HOOK" ]; then
		_log "ABSENT: $PRECOMMIT_HOOK not installed — run 'scripts/install-hooks.sh' first"
		exit 4
	fi
	if ! grep -q "pre-commit" "$PRECOMMIT_HOOK" 2>/dev/null; then
		_log "DRIFT: $PRECOMMIT_HOOK not managed by pre-commit framework"
		exit 1
	fi
else
	if ! command -v pre-commit >/dev/null 2>&1; then
		_log "error: pre-commit not in PATH — install with: brew install pre-commit"
		exit 3
	fi
	_log "installing pre-commit hooks..."
	pre-commit install --install-hooks
fi

# --- 2. git pre-push gate (pipeline gate) -------------------------------
# Write a wrapper script at $HOOKS_DIR/pre-push that exec's hooks/pre-
# push-pipeline-gate.sh by an absolute path it resolves AT RUNTIME via
# `git rev-parse --show-toplevel` (bare; git pre-push hooks run with
# cwd = repo worktree root). The in-tree gate
# script remains the source of truth (in-place edits take effect with
# no re-install); runtime resolution preserves relocation-safety so the
# wrapper survives `mv repo` AND git-worktree moves (per Phase 1 r1
# code-reviewer finding on absolute-path coupling regression).
#
# Wrapper (not symlink) because the gate uses `dirname "$0"` and its
# helper list-phase1-agents.sh uses `${BASH_SOURCE[0]}` to locate _lib.
# Under a symlink, both resolve to .git/hooks/, so the `dirname/../_lib`
# lookup tries .git/_lib (doesn't exist) instead of the real plugin's
# hooks/../_lib. macOS readlink lacks -f → can't portably canonicalize
# inside the gate. Wrapper sidesteps this by invoking via the real path.
GATE_SRC="hooks/pre-push-pipeline-gate.sh"
GATE_DST="$HOOKS_DIR/pre-push"

if [ ! -x "$GATE_SRC" ]; then
	_log "error: gate script missing at $GATE_SRC"
	exit 2
fi

# Canonical wrapper template — used for both install + drift check so
# they CAN'T drift apart. Quoted heredoc (no expansion at install time)
# so a REPO_ROOT containing $ or backticks can't corrupt the wrapper
# (Phase 1 silent-failure-hunter heredoc-expansion finding).
_wrapper_template() {
	cat <<'EOF'
#!/bin/sh
# Auto-generated by scripts/install-hooks.sh — DO NOT EDIT.
# Re-run scripts/install-hooks.sh to regenerate after plugin updates.
# REPO_ROOT resolved at runtime so the wrapper survives `mv repo` and
# works in git worktrees. Git invokes pre-push hooks with cwd = repo
# worktree root, so bare `git rev-parse --show-toplevel` works.
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || {
	echo "pre-push wrapper: cannot resolve REPO_ROOT (not in a git working tree?) — re-run scripts/install-hooks.sh" >&2
	exit 2
}
exec "$REPO_ROOT/hooks/pre-push-pipeline-gate.sh" "$@"
EOF
}

if [ "$CHECK_ONLY" = "1" ]; then
	if [ ! -x "$GATE_DST" ]; then
		_log "ABSENT: $GATE_DST not installed — run 'scripts/install-hooks.sh' first"
		exit 4
	fi
	# Byte-exact comparison against the canonical template so a hand-
	# edited or partially-corrupted wrapper is flagged as DRIFT instead
	# of being accepted by a substring match (Phase 1 silent-failure-
	# hunter weak-grep-check finding).
	_tmp_expected=$(mktemp)
	_wrapper_template >"$_tmp_expected"
	if ! cmp -s "$_tmp_expected" "$GATE_DST"; then
		rm -f "$_tmp_expected"
		_log "DRIFT: $GATE_DST contents differ from canonical wrapper template"
		_log "  Re-run 'scripts/install-hooks.sh' to regenerate."
		exit 1
	fi
	rm -f "$_tmp_expected"
else
	_log "installing pre-push gate at $GATE_DST..."
	# Use `rm` (not `rm -f`) so real I/O errors (perm-denied, immutable
	# bit, read-only FS) surface instead of being silently swallowed.
	if [ -e "$GATE_DST" ] || [ -L "$GATE_DST" ]; then
		rm "$GATE_DST"
	fi
	_wrapper_template >"$GATE_DST"
	chmod +x "$GATE_DST"
	# Post-write verification: assert the file we just wrote matches
	# the canonical template byte-for-byte. Catches partial writes,
	# weird filesystems where the redirect succeeds but the file ends
	# up with different content, and any future refactor that diverges
	# install from check (Phase 1 silent-failure-hunter no-post-write-
	# verify finding).
	_tmp_expected=$(mktemp)
	_wrapper_template >"$_tmp_expected"
	if ! cmp -s "$_tmp_expected" "$GATE_DST"; then
		rm -f "$_tmp_expected"
		_log "error: post-write verification failed — $GATE_DST contents do not match canonical template"
		exit 1
	fi
	rm -f "$_tmp_expected"
fi

# --- 3. exec-bit self-heal on all hook directories ---------------------
# v0.27.0 #173 Layer 5: re-assert chmod +x on every *.sh under hooks/ AND
# .claude/hooks/. The 2026-05-28 session bug was phase1-directive-
# pending-guard.sh in .claude/hooks/ losing its +x bit (cause unknown —
# possibly a stale file-mode entry from a worktree migration). Both
# directories are scanned so the self-heal covers the directory the bug
# actually struck (comment-analyzer Phase 1 r1 caught the mismatch
# between cited motivation and original Layer 5 scope).
shopt -s nullglob
HOOK_DIRS=(hooks .claude/hooks)
if [ "$CHECK_ONLY" = "1" ]; then
	non_exec=()
	for d in "${HOOK_DIRS[@]}"; do
		[ -d "$d" ] || continue
		for h in "$d"/*.sh; do
			[ -f "$h" ] || continue
			[ -x "$h" ] || non_exec+=("$h")
		done
	done
	if [ "${#non_exec[@]}" -gt 0 ]; then
		_log "DRIFT: hooks missing +x bit (cannot fire as PreToolUse handlers):"
		printf '  %s\n' "${non_exec[@]}" >&2
		_log "  Re-run 'scripts/install-hooks.sh' to fix."
		exit 1
	fi
else
	_log "asserting chmod +x on every *.sh under hooks/ + .claude/hooks/..."
	fixed=0
	scanned=0
	for d in "${HOOK_DIRS[@]}"; do
		[ -d "$d" ] || continue
		for h in "$d"/*.sh; do
			[ -f "$h" ] || continue
			scanned=$((scanned + 1))
			if [ ! -x "$h" ]; then
				chmod +x "$h"
				fixed=$((fixed + 1))
			fi
		done
	done
	_log "  scanned $scanned hook(s); +x restored on $fixed"
fi
shopt -u nullglob

# --- 4. Summary ----------------------------------------------------------
if [ "$CHECK_ONLY" = "1" ]; then
	_log "✓ all hooks installed + match expected layout"
else
	_log "✓ install complete:"
	_log "    $PRECOMMIT_HOOK → managed by pre-commit framework"
	_log "    $GATE_DST → wrapper script exec-ing $GATE_SRC"
	_log ""
	_log "Verify with: scripts/install-hooks.sh --check"
fi
